In [7]:
import aif360
import aix360
import pandas as pd
import numpy as np

In [8]:
data = pd.read_csv('heloc_dataset_v1.csv')

In [9]:
data.head()

RiskPerformance  ExternalRiskEstimate  MSinceOldestTradeOpen  \
0             Bad                    55                    144   
1             Bad                    61                     58   
2             Bad                    67                     66   
3             Bad                    66                    169   
4             Bad                    81                    333   

   MSinceMostRecentTradeOpen  AverageMInFile  NumSatisfactoryTrades  \
0                          4              84                     20   
1                         15              41                      2   
2                          5              24                      9   
3                          1              73                     28   
4                         27             132                     12   

   NumTrades60Ever2DerogPubRec  NumTrades90Ever2DerogPubRec  \
0                            3                            0   
1                            4                            4   
2                            0                            0   
3                            1                            1   
4                            0                            0   

   PercentTradesNeverDelq  MSinceMostRecentDelq  ...  PercentInstallTrades  \
0                      83                     2  ...                    43   
1                     100                    -7  ...                    67   
2                     100                    -7  ...                    44   
3                      93                    76  ...                    57   
4                     100                    -7  ...                    25   

   MSinceMostRecentInqexcl7days  NumInqLast6M  NumInqLast6Mexcl7days  \
0                             0             0                      0   
1                             0             0                      0   
2                             0             4                      4   
3                             0             5                      4   
4                             0             1                      1   

   NetFractionRevolvingBurden  NetFractionInstallBurden  \
0                          33                        -8   
1                           0                        -8   
2                          53                        66   
3                          72                        83   
4                          51                        89   

   NumRevolvingTradesWBalance  NumInstallTradesWBalance  \
0                           8                         1   
1                           0                        -8   
2                           4                         2   
3                           6                         4   
4                           3                         1   

   NumBank2NatlTradesWHighUtilization  PercentTradesWBalance  
0                                   1                     69  
1                                  -8                      0  
2                                   1                     86  
3                                   3                     91  
4                                   0                     80  

[5 rows x 24 columns]

In [44]:
# deep copy
data_encoded = data.copy(deep=True)

In [45]:
data_encoded.head()

RiskPerformance  ExternalRiskEstimate  MSinceOldestTradeOpen  \
0             Bad                    55                    144   
1             Bad                    61                     58   
2             Bad                    67                     66   
3             Bad                    66                    169   
4             Bad                    81                    333   

   MSinceMostRecentTradeOpen  AverageMInFile  NumSatisfactoryTrades  \
0                          4              84                     20   
1                         15              41                      2   
2                          5              24                      9   
3                          1              73                     28   
4                         27             132                     12   

   NumTrades60Ever2DerogPubRec  NumTrades90Ever2DerogPubRec  \
0                            3                            0   
1                            4                            4   
2                            0                            0   
3                            1                            1   
4                            0                            0   

   PercentTradesNeverDelq  MSinceMostRecentDelq  ...  PercentInstallTrades  \
0                      83                     2  ...                    43   
1                     100                    -7  ...                    67   
2                     100                    -7  ...                    44   
3                      93                    76  ...                    57   
4                     100                    -7  ...                    25   

   MSinceMostRecentInqexcl7days  NumInqLast6M  NumInqLast6Mexcl7days  \
0                             0             0                      0   
1                             0             0                      0   
2                             0             4                      4   
3                             0             5                      4   
4                             0             1                      1   

   NetFractionRevolvingBurden  NetFractionInstallBurden  \
0                          33                        -8   
1                           0                        -8   
2                          53                        66   
3                          72                        83   
4                          51                        89   

   NumRevolvingTradesWBalance  NumInstallTradesWBalance  \
0                           8                         1   
1                           0                        -8   
2                           4                         2   
3                           6                         4   
4                           3                         1   

   NumBank2NatlTradesWHighUtilization  PercentTradesWBalance  
0                                   1                     69  
1                                  -8                      0  
2                                   1                     86  
3                                   3                     91  
4                                   0                     80  

[5 rows x 24 columns]

In [46]:
# Encode output data
data_encoded["RiskPerformance"] = np.where((data_encoded.RiskPerformance=="Bad"), 0, 1)

In [47]:
data_encoded.head()

RiskPerformance  ExternalRiskEstimate  MSinceOldestTradeOpen  \
0                0                    55                    144   
1                0                    61                     58   
2                0                    67                     66   
3                0                    66                    169   
4                0                    81                    333   

   MSinceMostRecentTradeOpen  AverageMInFile  NumSatisfactoryTrades  \
0                          4              84                     20   
1                         15              41                      2   
2                          5              24                      9   
3                          1              73                     28   
4                         27             132                     12   

   NumTrades60Ever2DerogPubRec  NumTrades90Ever2DerogPubRec  \
0                            3                            0   
1                            4                            4   
2                            0                            0   
3                            1                            1   
4                            0                            0   

   PercentTradesNeverDelq  MSinceMostRecentDelq  ...  PercentInstallTrades  \
0                      83                     2  ...                    43   
1                     100                    -7  ...                    67   
2                     100                    -7  ...                    44   
3                      93                    76  ...                    57   
4                     100                    -7  ...                    25   

   MSinceMostRecentInqexcl7days  NumInqLast6M  NumInqLast6Mexcl7days  \
0                             0             0                      0   
1                             0             0                      0   
2                             0             4                      4   
3                             0             5                      4   
4                             0             1                      1   

   NetFractionRevolvingBurden  NetFractionInstallBurden  \
0                          33                        -8   
1                           0                        -8   
2                          53                        66   
3                          72                        83   
4                          51                        89   

   NumRevolvingTradesWBalance  NumInstallTradesWBalance  \
0                           8                         1   
1                           0                        -8   
2                           4                         2   
3                           6                         4   
4                           3                         1   

   NumBank2NatlTradesWHighUtilization  PercentTradesWBalance  
0                                   1                     69  
1                                  -8                      0  
2                                   1                     86  
3                                   3                     91  
4                                   0                     80  

[5 rows x 24 columns]

In [48]:
data_encoded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10459 entries, 0 to 10458
Data columns (total 24 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   RiskPerformance                     10459 non-null  int64
 1   ExternalRiskEstimate                10459 non-null  int64
 2   MSinceOldestTradeOpen               10459 non-null  int64
 3   MSinceMostRecentTradeOpen           10459 non-null  int64
 4   AverageMInFile                      10459 non-null  int64
 5   NumSatisfactoryTrades               10459 non-null  int64
 6   NumTrades60Ever2DerogPubRec         10459 non-null  int64
 7   NumTrades90Ever2DerogPubRec         10459 non-null  int64
 8   PercentTradesNeverDelq              10459 non-null  int64
 9   MSinceMostRecentDelq                10459 non-null  int64
 10  MaxDelq2PublicRecLast12M            10459 non-null  int64
 11  MaxDelqEver                         10459 non-null  int64
 12  NumT

In [51]:
for col in data_encoded.columns:
    print(data_encoded[col].unique())

[0 1]
[55 61 67 66 81 59 54 68 82 50 74 69 63 62 89 65 57 72 64 58 79 71 75 88
 51 70 78 86 90 76 73 83 87 -9 91 84 60 77 56 92 49 80 85 93 52 45 94 47
 43 48 40 39 44 36 37 53 34 46 33 42 41]
[144  58  66 169 333 137  88 148 324  79  96 311 274 256 262 184 131 244
  43 147 365  84  91 265 150 162 284 476 179 114 133 164 118 153 186 127
 116  21 318 230 293  37 255 209 398 326 478 197 243 183 176 368  -9 300
 168 277 174 126 409 419 282 134 155  70 294 357 106  85 204 151 307  17
 188 107 378 299  76 211 220 177 112 224 152 120 246 123 212 208 203 160
 103 159 241  61 178 198 258  41  14 233 252  -8 154  97 136 190 221 242
 132 245  27 139 222 218 156  82 247 129  93 321 338 195 145 352 205 135
 433 175 344 140 502 334 182 267 340 439 295 286 111 399  90  99 415 288
 163 281 407 191 180  69 363 253 170 325 474 234 432 130 251 280 125 408
 271 306 232 336 264 254 165 273 161 250 173  81 290 279 196  77  94  74
 219 369 266 375 291 122  72 269 343  78 149 115 353 128  39 192  51 351
 206

# Bias Detection

In [49]:
from aif360.metrics import BinaryLabelDatasetMetric
from aif360.datasets import BinaryLabelDataset

In [ ]:
privileged_groups = [{'OverTime': 0}]
unprivileged_groups = [{'OverTime': 1}]
favorable_label = 1 
unfavorable_label = 0

In [10]:
input_data = data.drop('RiskPerformance', 1)

In [12]:
input_data.head()

ExternalRiskEstimate  MSinceOldestTradeOpen  MSinceMostRecentTradeOpen  \
0                    55                    144                          4   
1                    61                     58                         15   
2                    67                     66                          5   
3                    66                    169                          1   
4                    81                    333                         27   

   AverageMInFile  NumSatisfactoryTrades  NumTrades60Ever2DerogPubRec  \
0              84                     20                            3   
1              41                      2                            4   
2              24                      9                            0   
3              73                     28                            1   
4             132                     12                            0   

   NumTrades90Ever2DerogPubRec  PercentTradesNeverDelq  MSinceMostRecentDelq  \
0                            0                      83                     2   
1                            4                     100                    -7   
2                            0                     100                    -7   
3                            1                      93                    76   
4                            0                     100                    -7   

   MaxDelq2PublicRecLast12M  ...  PercentInstallTrades  \
0                         3  ...                    43   
1                         0  ...                    67   
2                         7  ...                    44   
3                         6  ...                    57   
4                         7  ...                    25   

   MSinceMostRecentInqexcl7days  NumInqLast6M  NumInqLast6Mexcl7days  \
0                             0             0                      0   
1                             0             0                      0   
2                             0             4                      4   
3                             0             5                      4   
4                             0             1                      1   

   NetFractionRevolvingBurden  NetFractionInstallBurden  \
0                          33                        -8   
1                           0                        -8   
2                          53                        66   
3                          72                        83   
4                          51                        89   

   NumRevolvingTradesWBalance  NumInstallTradesWBalance  \
0                           8                         1   
1                           0                        -8   
2                           4                         2   
3                           6                         4   
4                           3                         1   

   NumBank2NatlTradesWHighUtilization  PercentTradesWBalance  
0                                   1                     69  
1                                  -8                      0  
2                                   1                     86  
3                                   3                     91  
4                                   0                     80  

[5 rows x 23 columns]

In [14]:
input_data.columns

Index(['ExternalRiskEstimate', 'MSinceOldestTradeOpen',
       'MSinceMostRecentTradeOpen', 'AverageMInFile', 'NumSatisfactoryTrades',
       'NumTrades60Ever2DerogPubRec', 'NumTrades90Ever2DerogPubRec',
       'PercentTradesNeverDelq', 'MSinceMostRecentDelq',
       'MaxDelq2PublicRecLast12M', 'MaxDelqEver', 'NumTotalTrades',
       'NumTradesOpeninLast12M', 'PercentInstallTrades',
       'MSinceMostRecentInqexcl7days', 'NumInqLast6M', 'NumInqLast6Mexcl7days',
       'NetFractionRevolvingBurden', 'NetFractionInstallBurden',
       'NumRevolvingTradesWBalance', 'NumInstallTradesWBalance',
       'NumBank2NatlTradesWHighUtilization', 'PercentTradesWBalance'],
      dtype='object')

In [16]:
input_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10459 entries, 0 to 10458
Data columns (total 23 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   ExternalRiskEstimate                10459 non-null  int64
 1   MSinceOldestTradeOpen               10459 non-null  int64
 2   MSinceMostRecentTradeOpen           10459 non-null  int64
 3   AverageMInFile                      10459 non-null  int64
 4   NumSatisfactoryTrades               10459 non-null  int64
 5   NumTrades60Ever2DerogPubRec         10459 non-null  int64
 6   NumTrades90Ever2DerogPubRec         10459 non-null  int64
 7   PercentTradesNeverDelq              10459 non-null  int64
 8   MSinceMostRecentDelq                10459 non-null  int64
 9   MaxDelq2PublicRecLast12M            10459 non-null  int64
 10  MaxDelqEver                         10459 non-null  int64
 11  NumTotalTrades                      10459 non-null  int64
 12  NumT

In [38]:
output_data = data[['RiskPerformance']]

In [39]:
output_data.head()

RiskPerformance
0             Bad
1             Bad
2             Bad
3             Bad
4             Bad

In [40]:
output_data['RiskPerformance'].unique()

array(['Bad', 'Good'], dtype=object)

/Users/saishruthi.tn@ibm.com/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [43]:
output_data

RiskPerformance
0                    0
1                    0
2                    0
3                    0
4                    0
...                ...
10454                1
10455                0
10456                0
10457                0
10458                0

[10459 rows x 1 columns]

In [52]:
data = pd.read_csv('2018_public_lar_csv.csv')

/Users/saishruthi.tn@ibm.com/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (4,5,22,23,24,26,27,28,29,30,31,32,33,38,43,44,46) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [53]:
len(data)

4007401

In [100]:
g_data = data.loc[(data['applicant_sex'].isin([1,2]) == 1)]

In [101]:
len(g_data)

3369933

In [102]:
g_data['activity_year'].unique()

array([2018])

In [103]:
input_data = g_data[0:20000]

In [104]:
input_data.head()

activity_year                   lei  derived_msa_md state_code county_code  \
0           2018  549300HW662MN1WU8550           40140         CA        6071   
1           2018  549300HW662MN1WU8550           33460         MN       27141   
2           2018  549300HW662MN1WU8550           47664         MI       26125   
3           2018  549300HW662MN1WU8550           12060         GA       13057   
4           2018  549300HW662MN1WU8550           29820         NV       32003   

  census_tract conforming_loan_limit derived_loan_product_type  \
0  6.07101e+09                     C            FHA:First Lien   
1   2.7141e+10                     C   Conventional:First Lien   
2  2.61252e+10                     C   Conventional:First Lien   
3  1.30571e+10                     C   Conventional:First Lien   
4   3.2003e+10                     C   Conventional:First Lien   

              derived_dwelling_category       derived_ethnicity  ...  \
0  Single Family (1-4 Units):Site-Built      Hispanic or Latino  ...   
1  Single Family (1-4 Units):Site-Built  Not Hispanic or Latino  ...   
2  Single Family (1-4 Units):Site-Built  Not Hispanic or Latino  ...   
3  Single Family (1-4 Units):Site-Built  Not Hispanic or Latino  ...   
4  Single Family (1-4 Units):Site-Built  Not Hispanic or Latino  ...   

  denial_reason_2 denial_reason_3  denial_reason_4  tract_population  \
0             NaN             NaN              NaN            6022.0   
1             NaN             NaN              NaN           11123.0   
2             NaN             NaN              NaN            2632.0   
3             NaN             NaN              NaN            9836.0   
4             NaN             NaN              NaN            7804.0   

   tract_minority_population_percent  ffiec_msa_md_median_family_income  \
0                              36.28                            65800.0   
1                               4.14                            93600.0   
2                               9.19                            83200.0   
3                              35.86                            74400.0   
4                              58.84                            64800.0   

   tract_to_msa_income_percentage  tract_owner_occupied_units  \
0                            68.0                      1214.0   
1                            93.0                      2986.0   
2                           101.0                       719.0   
3                            61.0                      1322.0   
4                            94.0                      1161.0   

   tract_one_to_four_family_homes  tract_median_age_of_housing_units  
0                          2110.0                               29.0  
1                          3441.0                               17.0  
2                           938.0                               63.0  
3                          2522.0                               15.0  
4                          2569.0                               10.0  

[5 rows x 99 columns]

In [112]:
selected_data  = input_data[['conforming_loan_limit','preapproval','loan_term', 'aus_1', 
                   'applicant_age', 'applicant_credit_score_type', 'combined_loan_to_value_ratio', 
                   'property_value', 'income', 'debt_to_income_ratio',
                   'loan_amount', 'applicant_ethnicity_1', 'applicant_race_1', 'applicant_sex', 'action_taken']]

In [ ]:
selected_data.isna().sum()

In [113]:
len(selected_data.columns)

15

In [114]:
selected_data.head()

conforming_loan_limit  preapproval loan_term  aus_1 applicant_age  \
0                     C          2.0       360    1.0         25-34   
1                     C          2.0       360    1.0         25-34   
2                     C          2.0       360    1.0         25-34   
3                     C          2.0       360    1.0         25-34   
4                     C          2.0       360    1.0         25-34   

   applicant_credit_score_type combined_loan_to_value_ratio property_value  \
0                          3.0                         96.5         215000   
1                          1.0                           97         225000   
2                          3.0                           80         315000   
3                          3.0                           97         255000   
4                          2.0                        69.23         325000   

   income debt_to_income_ratio  loan_amount  applicant_ethnicity_1  \
0   120.0                   45     205000.0                    1.0   
1    58.0                   43     215000.0                    2.0   
2    89.0             20%-<30%     245000.0                    2.0   
3    78.0                   38     245000.0                    2.0   
4    41.0                   49     225000.0                    2.0   

   applicant_race_1  applicant_sex  action_taken  
0               5.0            1.0           1.0  
1               5.0            1.0           1.0  
2               5.0            1.0           1.0  
3               5.0            1.0           1.0  
4               2.0            1.0           1.0

In [116]:
selected_data.isna().sum()

conforming_loan_limit              1
preapproval                        0
loan_term                          0
aus_1                              0
applicant_age                      0
applicant_credit_score_type        0
combined_loan_to_value_ratio    2184
property_value                  2196
income                            30
debt_to_income_ratio            2221
loan_amount                        0
applicant_ethnicity_1              0
applicant_race_1                   0
applicant_sex                      0
action_taken                       0
dtype: int64

In [115]:
for col in selected_data.columns:
    if col in ['income', 'loan_amount', 'property_value', 'combined_loan_to_value_ratio']:
        continue
    print(col)
    print(selected_data[col].unique())
    print('--------------------------------')

conforming_loan_limit
['C' 'NC' nan]
--------------------------------
preapproval
[2.]
--------------------------------
loan_term
[360 180 240 120 84 300 12 336 168 348 324 60 96 312 264 288]
--------------------------------
aus_1
[1. 2. 4. 6.]
--------------------------------
applicant_age
['25-34' '<25' '65-74' '45-54' '55-64' '35-44' '>74']
--------------------------------
applicant_credit_score_type
[3. 1. 2. 9.]
--------------------------------
debt_to_income_ratio
['45' '43' '20%-<30%' '38' '49' '30%-<36%' '48' '47' '39' '50%-60%' nan
 '41' '40' '42' '44' '36' '>60%' '37' '46' '<20%']
--------------------------------
applicant_ethnicity_1
[ 1.  2.  3. 14. 13. 11.]
--------------------------------
applicant_race_1
[ 5.  2.  6.  3. 23.  4.  1. 25. 44. 21. 27. 22. 26.]
--------------------------------
applicant_sex
[1. 2.]
--------------------------------
action_taken
[1. 5. 3. 2. 4.]
--------------------------------
